version: '3.8'

services:
  user-service:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - HOST=mysql
      - DB_USER=root
      - PASSWORD=yourpassword
      - DB_NAME=solid_node_db
      - DIALECT=mysql
      - PORT=3001
    depends_on:
      - mysql
    volumes:
      - ./server:/app
      - /app/node_modules

  # order-service:
  #   build:
  #     context: ./order
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3002:3002"
  #   environment:
  #     - HOST=mysql
  #     - DB_USER=root
  #     - PASSWORD=yourpassword
  #     - DB_NAME=solid_node_db
  #     - DIALECT=mysql
  #     - PORT=3002
  #   depends_on:
  #     - mysql
  #   volumes:
  #     - ./order:/app
  #     - /app/node_modules

  # payment-service:
  #   build:
  #     context: ./payment
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3003:3003"
  #   environment:
  #     - HOST=mysql
  #     - DB_USER=root
  #     - PASSWORD=yourpassword
  #     - DB_NAME=solid_node_db
  #     - DIALECT=mysql
  #     - PORT=3003
  #   depends_on:
  #     - mysql
  #   volumes:
  #     - ./payment:/app
  #     - /app/node_modules

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      # - order-service
      # - payment-service
    environment:
      - NODE_ENV=production

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: solid_node_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
