apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend:latest
          ports:
            - containerPort: 3001
          env:
            - name: HOST
              value: "mysql"
            - name: DB_USER
              value: "root"
            - name: PASSWORD
              value: "yourpassword"
            - name: DB_NAME
              value: "solid_node_db"
            - name: DIALECT
              value: "mysql"
            - name: PORT
              value: "3001"
            - name: EMAIL_USER
              value: "noreplay.primexlogistics@gmail.com"
            - name: EMAIL_PASS
              value: "ruus rlkr ojjn ccci"
            - name: SECRET_KEY
              value: "VotreCléSecrèteIci"
            - name: SALT_ROUNDS
              value: "10"
